### ISSUE TITLE
reverify tdf sep2017

### ISSUE THREAD

**Issue by kr1shna-opensource** [kr1shna-opensource/qa#21]
* [91007](https://bugs.documentfoundation.org/show_bug.cgi?id=91007) [fcfe2st.xls](http://www.exinfm.com/excel%20files/fcfe2st.xls)
* [91006](https://bugs.documentfoundation.org/show_bug.cgi?id=91006) [implprem.xls](http://www.exinfm.com/excel%20files/implprem.xls)
* [51671](https://bugs.documentfoundation.org/show_bug.cgi?id=51671) [legend.xls](https://bugs.documentfoundation.org/attachment.cgi?id=63733&action=edit)

**Comment by kr1shnas** [comment]
* [108820](https://bugs.documentfoundation.org/show_bug.cgi?id=108820)  [Footnote number table issue.odt](https://bugs.documentfoundation.org/attachment.cgi?id=134338&action=edit)

**Comment by kr1shnas** [comment]
* [107786](https://bugs.documentfoundation.org/show_bug.cgi?id=107786)  [1.doc](https://bugs.documentfoundation.org/attachment.cgi?id=133249&action=edit)
*test on daily build only

**Comment by kr1shnas** [comment]
* [106724](https://bugs.documentfoundation.org/show_bug.cgi?id=106724)  [targeted cover letter (Simple comment).docx](https://bugs.documentfoundation.org/attachment.cgi?id=132104&action=edit)
* [106724](https://bugs.documentfoundation.org/show_bug.cgi?id=106724)  [targeted cover letter (Simple comment with citation).docx](https://bugs.documentfoundation.org/attachment.cgi?id=132105&action=edit)
*send email to ml
*test on daily build only

**Comment by kr1shnas** [comment]
* [103664](https://bugs.documentfoundation.org/show_bug.cgi?id=103664)  [wingdingssymbols.docx](https://bugs.documentfoundation.org/attachment.cgi?id=128453&action=edit)
*verify symbols, total 4, screenshots on device

**Comment by kr1shna-opensource** [comment]
[search](https://bugs.documentfoundation.org/buglist.cgi?bug_status=RESOLVED&chfieldfrom=14d&chfieldto=Now&component=Calc&component=Chart&component=Draw&component=filters%20and%20storage&component=Impress&component=LibreOffice&component=Writer&f1=commenter&list_id=732365&o1=notsubstring&order=Last%20Changed&query_format=advanced&resolution=FIXED&v1=krishna%40grrlz.net) -4
* daily build only

* [112101](https://bugs.documentfoundation.org/show_bug.cgi?id=112101)  [dfd03515-aee4-4cef-ad76-8fbc09f61926.odt](http://bugs.documentfoundation.org/attachment.cgi?id=135865&action=edit)

* [104602](https://bugs.documentfoundation.org/show_bug.cgi?id=104602)  [Example.docx](http://bugs.documentfoundation.org/attachment.cgi?id=129522&action=edit)

* [112163](https://bugs.documentfoundation.org/show_bug.cgi?id=112163)  [ceb89471-7258-4257-970d-d2a4af443d1d.odt](http://bugs.documentfoundation.org/attachment.cgi?id=135935&action=edit)

* [112164](https://bugs.documentfoundation.org/show_bug.cgi?id=112164)  [c2dfc5bd-8366-40e7-b862-55e13fdc52dc.odt](http://bugs.documentfoundation.org/attachment.cgi?id=135937&action=edit)

**Comment by kr1shna-opensource** [comment]
change of mind, see label, closing
