### ISSUE TITLE
verify tdf sep0917

### ISSUE THREAD

**Issue by kr1shna-opensource** [kr1shna-opensource/qa#22]
* [89892](https://bugs.documentfoundation.org/show_bug.cgi?id=89892) [pwd.odt](http://bugs.documentfoundation.org/attachment.cgi?id=115046&action=edit) 1

**updated: 090917**
<del>[search](https://bugs.documentfoundation.org/buglist.cgi?bug_status=RESOLVED&chfieldfrom=2017-03-01&chfieldto=2017-03-31&component=Writer&order=Bug%20Number&query_format=advanced&resolution=FIXED) -1</del>
<del>* [106799](https://bugs.documentfoundation.org/show_bug.cgi?id=106799) [TTPMarkNoCellMark.doc](http://bugs.documentfoundation.org/attachment.cgi?id=132174&action=edit)</del>

**abandoned, no resume support, large file, deleted**
<del>* [104079](https://bugs.documentfoundation.org/show_bug.cgi?id=104079) Manual.rtf
[abi3241-1.rtf.LO5M_CLAYOUTLIN-pair-s.pdf ](http://bugs.documentfoundation.org/attachment.cgi?id=128915&action=edit)
*download pdf attachment</del>

**Comment by kr1shnas** [comment]
**verify on daily build**
* [107016](https://bugs.documentfoundation.org/show_bug.cgi?id=107016)  [39053_extracted.emf](https://bugs.documentfoundation.org/attachment.cgi?id=132516&action=edit)

Expected Results:
Black border around box should be displayed

**no**
5.4.0.0.alpha0+ [ build id: 3902bb7 ]

* [107019](https://bugs.documentfoundation.org/show_bug.cgi?id=107019)  [image17.emf](https://bugs.documentfoundation.org/attachment.cgi?id=132401&action=edit)

**no**
5.4.0.0.alpha0+ [ build id: 3902bb7 ]

Expected Results:
Curve is appearing in chart

**Comment by kr1shna-opensource** [comment]
* [111566](https://bugs.documentfoundation.org/show_bug.cgi?id=111566)  [passu1234.xls](https://bugs.documentfoundation.org/attachment.cgi?id=135471&action=edit)
*Password is 1234

**Comment by kr1shna-opensource** [comment]
change of mind, see label, closing

**Comment by kr1shna-opensource** [comment]
consolidated into https://github.com/kr1shna-opensource/qa/issues/24
